# Use the official Node.js runtime as a base image
FROM node:16-buster

# Set the working directory to /app
WORKDIR /app

COPY package*.json ./
# COPY .env /app

# Copy the current directory contents into the container at /app
COPY /src /app/src

# Install any needed packages specified in package.json
RUN npm install -g nodemon ts-node
RUN npm install

# We don't need the standalone Chromium


# Expose port 4000
EXPOSE 4000

# Define the command to start the server
CMD nodemon -L src/express.ts